services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always

    ports:
      - "1433:1433"

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"   # ⚠️ change ce mot de passe
      MSSQL_PID: "Express"               # version gratuite

    volumes:
      - sqlserver_data:/var/opt/mssql

    networks:
      - monitoring_shared

    mem_limit: 1g   # 🔥 IMPORTANT pour ton VPS 4GB

volumes:
  sqlserver_data:

networks:
  monitoring_shared:
    external: true
